### PR TITLE
Fix `./` paths and other relative paths for create-partykit

### LINKED ISSUE #341: error with cli and ./ file path
Not a biggie, but when prompted for file name, suggested has ./*

So naturally I would do like ./new-app but it errors

```
Invalid path. Please use a path like "randomName" or just "." to use the current directory. You entered "./test-party"
/Users/name_here/.npm/_npx/cadd21533ff9f374/node_modules/create-partykit/src/index.tsx:182
        reject(new Error("Invalid path"));
               ^


Error: Invalid path
```

### PR DESCRIPTION
**Pull request by jevakallio**
Fixes #341 and closes #309. Also expands the legal paths to any relative path from the current working directory.

Valid paths:
```
.
./
../
./hello
../hello
../../hello
hello
hello/world
```

Invalid paths
```
hello world
./hello world
hello.json
/hello

```

As per last invalid path example, we still don't allow absolute paths. We could enable this as well, but it would have required changing the path resolution code elsewhere, and writing to absolute paths is most likely unintended, so I didn't enable it for now.

### CODE REVIEW

File: packages/create-partykit/src/index.tsx [hunk 1]
```diff
@@ -198,14 +198,25 @@ export async function init(options: {
...
+        );
+        reject(new Error("Absolute paths not supported"));
+      }
 
-      if (!isValidPathRegex.test(text || randomName)) {
+      const parsed = path.parse(text);
+      const isValidPathRegex = /^\.*?([a-zA-Z0-9_-]{0,}\/)*[a-zA-Z0-9_-]+$/;
+      const isValidPath = (path: string) =>
+        path === "." || path === ".." || isValidPathRegex.test(path);
+      if (!isValidPath(parsed.base) || !isValidPath(parsed.name)) {
```
Comment (jevakallio) [inline packages/create-partykit/src/index.tsx:216]: Parsing the base path and the base name separately to make the regex simpler

File: packages/create-partykit/src/index.tsx [hunk 2]
```diff
@@ -198,14 +198,25 @@ export async function init(options: {
...
+          )
+        );
+        reject(new Error("Absolute paths not supported"));
+      }
 
-      if (!isValidPathRegex.test(text || randomName)) {
+      const parsed = path.parse(text);
+      const isValidPathRegex = /^\.*?([a-zA-Z0-9_-]{0,}\/)*[a-zA-Z0-9_-]+$/;
+      const isValidPath = (path: string) =>
+        path === "." || path === ".." || isValidPathRegex.test(path);
```
Comment (jevakallio) [inline packages/create-partykit/src/index.tsx:215]: Checking for relative path parts separately to make the regex simpelr

**Review by threepointone — APPROVED** [review]
Looks great, thanks for the fix!
